/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * How to setup clock using clock driver functions:
 *
 * 1. Setup clock sources.
 *
 * 2. Set up wait states of the flash.
 *
 * 3. Set up all dividers.
 *
 * 4. Set up all selectors to provide selected clocks.
 *
 */

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Clocks v20.0
processor: MCXA176
package_id: MCXA176VLL
mcu_data: ksdk2_0
processor_version: 26.03.20
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

#include "fsl_clock.h"
#include "clock_config.h"
#include "fsl_spc.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
/* System clock frequency. */
extern uint32_t SystemCoreClock;

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
    BOARD_BootClockFROHF180M();
}

/*******************************************************************************
 ******************** Configuration BOARD_BootClockFRO12M **********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFRO12M
outputs:
- {id: BUS_clock.outFreq, value: 22.5 MHz}
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_45M_clock.outFreq, value: 45 MHz}
- {id: CPU_clock.outFreq, value: 45 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 45 MHz}
- {id: FRO_HF_clock.outFreq, value: 45 MHz}
- {id: MAIN_clock.outFreq, value: 45 MHz}
- {id: Slow_clock.outFreq, value: 7.5 MHz}
- {id: System_clock.outFreq, value: 45 MHz}
- {id: TRACE_clock.outFreq, value: 45 MHz}
- {id: UTICK0_clock.outFreq, value: 1 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: VDD_CORE, value: voltage_1v2}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFRO12M configuration
 ******************************************************************************/
void BOARD_BootClockFRO12M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(45000000U); /*!< Enable FRO HF 45000000Hz output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1);                /* !< Switch CMP1 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);             /* !< Switch CTIMER2 to  */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);             /* !< Switch CTIMER3 to  */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);             /* !< Switch CTIMER4 to  */
            break;
        case kClockModule_DAC0Clk:
            CLOCK_AttachClk(kNONE_to_DAC0);                /* !< Switch DAC0 to  */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);            /* !< Switch FLEXCAN0 to  */
            break;
        case kClockModule_FLEXIO0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXIO0);             /* !< Switch FLEXIO0 to  */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);            /* !< Switch I3C0FCLK to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPI2C1Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C1);              /* !< Switch LPI2C1 to  */
            break;
        case kClockModule_LPI2C2Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C2);              /* !< Switch LPI2C2 to  */
            break;
        case kClockModule_LPI2C3Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C3);              /* !< Switch LPI2C3 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPSPI1Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI1);              /* !< Switch LPSPI1 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_LPUART4Clk:
            CLOCK_AttachClk(kNONE_to_LPUART4);             /* !< Switch LPUART4 to  */
            break;
        case kClockModule_OSTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);             /* !< Switch OSTIMER to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_USB0ClkClk:
            CLOCK_AttachClk(kNONE_to_USB0);                /* !< Switch USB0 to  */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFRO12M(void)
{
    uint32_t coreFreq;
    spc_active_mode_core_ldo_option_t ldoOption;
    spc_sram_voltage_config_t sramOption;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFRO12M_CORE_CLOCK) {
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
    }
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFRO12M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
    }

    BOARD_BootClockFRO12M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_DAC0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_FLEXIO0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPI2C1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPI2C2Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPI2C3Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPSPI1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_LPUART4Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_OSTIMER0Clk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_USB0ClkClk);
    BOARD_BootClockFRO12M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFRO12M_CORE_CLOCK;
}
/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF45M *********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFROHF45M
outputs:
- {id: BUS_clock.outFreq, value: 22.5 MHz}
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_45M_clock.outFreq, value: 45 MHz}
- {id: CPU_clock.outFreq, value: 45 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 45 MHz}
- {id: FRO_HF_clock.outFreq, value: 45 MHz}
- {id: MAIN_clock.outFreq, value: 45 MHz}
- {id: Slow_clock.outFreq, value: 7.5 MHz}
- {id: System_clock.outFreq, value: 45 MHz}
- {id: TRACE_clock.outFreq, value: 45 MHz}
- {id: UTICK0_clock.outFreq, value: 1 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: VDD_CORE, value: voltage_1v2}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFROHF45M configuration
 ******************************************************************************/
void BOARD_BootClockFROHF45M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(45000000U); /*!< Enable FRO HF 45000000Hz output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1);                /* !< Switch CMP1 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);             /* !< Switch CTIMER2 to  */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);             /* !< Switch CTIMER3 to  */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);             /* !< Switch CTIMER4 to  */
            break;
        case kClockModule_DAC0Clk:
            CLOCK_AttachClk(kNONE_to_DAC0);                /* !< Switch DAC0 to  */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);            /* !< Switch FLEXCAN0 to  */
            break;
        case kClockModule_FLEXIO0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXIO0);             /* !< Switch FLEXIO0 to  */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);            /* !< Switch I3C0FCLK to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPI2C1Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C1);              /* !< Switch LPI2C1 to  */
            break;
        case kClockModule_LPI2C2Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C2);              /* !< Switch LPI2C2 to  */
            break;
        case kClockModule_LPI2C3Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C3);              /* !< Switch LPI2C3 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPSPI1Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI1);              /* !< Switch LPSPI1 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_LPUART4Clk:
            CLOCK_AttachClk(kNONE_to_LPUART4);             /* !< Switch LPUART4 to  */
            break;
        case kClockModule_OSTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);             /* !< Switch OSTIMER to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_USB0ClkClk:
            CLOCK_AttachClk(kNONE_to_USB0);                /* !< Switch USB0 to  */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFROHF45M(void)
{
    uint32_t coreFreq;
    spc_active_mode_core_ldo_option_t ldoOption;
    spc_sram_voltage_config_t sramOption;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFROHF45M_CORE_CLOCK) {
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
    }
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFROHF45M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
    }

    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_DAC0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_FLEXIO0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPI2C1Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPI2C2Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPI2C3Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPSPI1Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_LPUART4Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_OSTIMER0Clk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_USB0ClkClk);
    BOARD_BootClockFROHF45M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFROHF45M_CORE_CLOCK;
}
/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF60M *********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFROHF60M
outputs:
- {id: BUS_clock.outFreq, value: 22.5 MHz}
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_45M_clock.outFreq, value: 45 MHz}
- {id: CPU_clock.outFreq, value: 45 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 45 MHz}
- {id: FRO_HF_clock.outFreq, value: 45 MHz}
- {id: MAIN_clock.outFreq, value: 45 MHz}
- {id: Slow_clock.outFreq, value: 7.5 MHz}
- {id: System_clock.outFreq, value: 45 MHz}
- {id: TRACE_clock.outFreq, value: 45 MHz}
- {id: UTICK0_clock.outFreq, value: 1 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: VDD_CORE, value: voltage_1v2}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFROHF60M configuration
 ******************************************************************************/
void BOARD_BootClockFROHF60M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(45000000U); /*!< Enable FRO HF 45000000Hz output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1);                /* !< Switch CMP1 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);             /* !< Switch CTIMER2 to  */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);             /* !< Switch CTIMER3 to  */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);             /* !< Switch CTIMER4 to  */
            break;
        case kClockModule_DAC0Clk:
            CLOCK_AttachClk(kNONE_to_DAC0);                /* !< Switch DAC0 to  */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);            /* !< Switch FLEXCAN0 to  */
            break;
        case kClockModule_FLEXIO0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXIO0);             /* !< Switch FLEXIO0 to  */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);            /* !< Switch I3C0FCLK to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPI2C1Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C1);              /* !< Switch LPI2C1 to  */
            break;
        case kClockModule_LPI2C2Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C2);              /* !< Switch LPI2C2 to  */
            break;
        case kClockModule_LPI2C3Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C3);              /* !< Switch LPI2C3 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPSPI1Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI1);              /* !< Switch LPSPI1 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_LPUART4Clk:
            CLOCK_AttachClk(kNONE_to_LPUART4);             /* !< Switch LPUART4 to  */
            break;
        case kClockModule_OSTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);             /* !< Switch OSTIMER to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_USB0ClkClk:
            CLOCK_AttachClk(kNONE_to_USB0);                /* !< Switch USB0 to  */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFROHF60M(void)
{
    uint32_t coreFreq;
    spc_active_mode_core_ldo_option_t ldoOption;
    spc_sram_voltage_config_t sramOption;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFROHF60M_CORE_CLOCK) {
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
    }
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFROHF60M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
    }

    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_DAC0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_FLEXIO0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPI2C1Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPI2C2Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPI2C3Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPSPI1Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_LPUART4Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_OSTIMER0Clk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_USB0ClkClk);
    BOARD_BootClockFROHF60M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFROHF60M_CORE_CLOCK;
}
/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF90M *********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFROHF90M
outputs:
- {id: BUS_clock.outFreq, value: 22.5 MHz}
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_45M_clock.outFreq, value: 45 MHz}
- {id: CPU_clock.outFreq, value: 45 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 45 MHz}
- {id: FRO_HF_clock.outFreq, value: 45 MHz}
- {id: MAIN_clock.outFreq, value: 45 MHz}
- {id: Slow_clock.outFreq, value: 7.5 MHz}
- {id: System_clock.outFreq, value: 45 MHz}
- {id: TRACE_clock.outFreq, value: 45 MHz}
- {id: UTICK0_clock.outFreq, value: 1 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: VDD_CORE, value: voltage_1v2}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFROHF90M configuration
 ******************************************************************************/
void BOARD_BootClockFROHF90M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(45000000U); /*!< Enable FRO HF 45000000Hz output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1);                /* !< Switch CMP1 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);             /* !< Switch CTIMER2 to  */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);             /* !< Switch CTIMER3 to  */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);             /* !< Switch CTIMER4 to  */
            break;
        case kClockModule_DAC0Clk:
            CLOCK_AttachClk(kNONE_to_DAC0);                /* !< Switch DAC0 to  */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);            /* !< Switch FLEXCAN0 to  */
            break;
        case kClockModule_FLEXIO0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXIO0);             /* !< Switch FLEXIO0 to  */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);            /* !< Switch I3C0FCLK to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPI2C1Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C1);              /* !< Switch LPI2C1 to  */
            break;
        case kClockModule_LPI2C2Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C2);              /* !< Switch LPI2C2 to  */
            break;
        case kClockModule_LPI2C3Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C3);              /* !< Switch LPI2C3 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPSPI1Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI1);              /* !< Switch LPSPI1 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_LPUART4Clk:
            CLOCK_AttachClk(kNONE_to_LPUART4);             /* !< Switch LPUART4 to  */
            break;
        case kClockModule_OSTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);             /* !< Switch OSTIMER to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_USB0ClkClk:
            CLOCK_AttachClk(kNONE_to_USB0);                /* !< Switch USB0 to  */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFROHF90M(void)
{
    uint32_t coreFreq;
    spc_active_mode_core_ldo_option_t ldoOption;
    spc_sram_voltage_config_t sramOption;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFROHF90M_CORE_CLOCK) {
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
    }
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFROHF90M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
    }

    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_DAC0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_FLEXIO0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPI2C1Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPI2C2Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPI2C3Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPSPI1Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_LPUART4Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_OSTIMER0Clk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_USB0ClkClk);
    BOARD_BootClockFROHF90M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFROHF90M_CORE_CLOCK;
}
/*******************************************************************************
 ******************* Configuration BOARD_BootClockFROHF180M ********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockFROHF180M
called_from_default_init: true
outputs:
- {id: BUS_clock.outFreq, value: 90 MHz}
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_45M_clock.outFreq, value: 45 MHz}
- {id: CPU_clock.outFreq, value: 180 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 180 MHz}
- {id: FRO_HF_clock.outFreq, value: 180 MHz}
- {id: MAIN_clock.outFreq, value: 180 MHz}
- {id: Slow_clock.outFreq, value: 30 MHz}
- {id: System_clock.outFreq, value: 180 MHz}
- {id: TRACE_clock.outFreq, value: 20 MHz}
- {id: UTICK0_clock.outFreq, value: 1 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: VDD_CORE, value: voltage_1v2}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
- {id: MRCC.TRACE_CLKDIV.scale, value: '9'}
- {id: SCG.FREQ_SEL.scale, value: '1', locked: true}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockFROHF180M configuration
 ******************************************************************************/
void BOARD_BootClockFROHF180M_InitClockModule(clock_module_t module)
{

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(180000000U); /*!< Enable FRO HF 180000000Hz output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1);                /* !< Switch CMP1 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);             /* !< Switch CTIMER2 to  */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);             /* !< Switch CTIMER3 to  */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);             /* !< Switch CTIMER4 to  */
            break;
        case kClockModule_DAC0Clk:
            CLOCK_AttachClk(kNONE_to_DAC0);                /* !< Switch DAC0 to  */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);            /* !< Switch FLEXCAN0 to  */
            break;
        case kClockModule_FLEXIO0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXIO0);             /* !< Switch FLEXIO0 to  */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);            /* !< Switch I3C0FCLK to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPI2C1Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C1);              /* !< Switch LPI2C1 to  */
            break;
        case kClockModule_LPI2C2Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C2);              /* !< Switch LPI2C2 to  */
            break;
        case kClockModule_LPI2C3Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C3);              /* !< Switch LPI2C3 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPSPI1Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI1);              /* !< Switch LPSPI1 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_LPUART4Clk:
            CLOCK_AttachClk(kNONE_to_LPUART4);             /* !< Switch LPUART4 to  */
            break;
        case kClockModule_OSTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);             /* !< Switch OSTIMER to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 9U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 9 */
            break;
        case kClockModule_USB0ClkClk:
            CLOCK_AttachClk(kNONE_to_USB0);                /* !< Switch USB0 to  */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockFROHF180M(void)
{
    uint32_t coreFreq;
    spc_active_mode_core_ldo_option_t ldoOption;
    spc_sram_voltage_config_t sramOption;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKFROHF180M_CORE_CLOCK) {
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x4U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
    }
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKFROHF180M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x4U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
    }

    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_DAC0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_FLEXIO0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPI2C1Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPI2C2Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPI2C3Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPSPI1Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_LPUART4Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_OSTIMER0Clk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_USB0ClkClk);
    BOARD_BootClockFROHF180M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKFROHF180M_CORE_CLOCK;
}
/*******************************************************************************
 ******************** Configuration BOARD_BootClockPLL180M *********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockPLL180M
outputs:
- {id: BUS_clock.outFreq, value: 22.5 MHz}
- {id: CLK_1M_clock.outFreq, value: 1 MHz}
- {id: CLK_45M_clock.outFreq, value: 45 MHz}
- {id: CPU_clock.outFreq, value: 45 MHz}
- {id: FREQME_reference_clock.outFreq, value: 12 MHz}
- {id: FREQME_target_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_DIV_clock.outFreq, value: 12 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 45 MHz}
- {id: FRO_HF_clock.outFreq, value: 45 MHz}
- {id: MAIN_clock.outFreq, value: 45 MHz}
- {id: PLL1_DIV_clock.outFreq, value: 180 MHz}
- {id: PLL1_clock.outFreq, value: 180 MHz}
- {id: Slow_clock.outFreq, value: 7.5 MHz}
- {id: System_clock.outFreq, value: 45 MHz}
- {id: TRACE_clock.outFreq, value: 45 MHz}
- {id: UTICK0_clock.outFreq, value: 1 MHz}
- {id: WWDT0_clock.outFreq, value: 1 MHz}
settings:
- {id: PLL_MODE, value: Normal}
- {id: VDD_CORE, value: voltage_1v2}
- {id: FROHFDIV_SYSCON_FROHFDIV_HALT, value: RUN}
- {id: FROLFDIV_SYSCON_FROLFDIV_HALT, value: RUN}
- {id: PLL1CLKDIV_SYSCON_PLL1CLKDIV_HALT, value: RUN}
- {id: SCG.MDIV.scale, value: '8'}
- {id: SCG.PLL1_CLKSEL.sel, value: SCG.CLK_45M_clock}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Code for BOARD_BootClockPLL180M configuration
 ******************************************************************************/
void BOARD_BootClockPLL180M_InitClockModule(clock_module_t module)
{
    const pll_setup_t pll1Setup = {
        .pllctrl = SCG_SPLLCTRL_SOURCE(1U) | SCG_SPLLCTRL_SELI(7U) | SCG_SPLLCTRL_SELP(3U),
        .pllndiv = SCG_SPLLNDIV_NDIV(1U),
        .pllpdiv = SCG_SPLLPDIV_PDIV(1U),
        .pllmdiv = SCG_SPLLMDIV_MDIV(8U),
        .pllRate = 180000000U
    };

    switch(module) {
        case kClockModule_FIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_HF, 1U);       /* !< Set SYSCON.FROHFDIV divider to value 1 */
            CLOCK_SetupFROHFClocking(45000000U); /*!< Enable FRO HF 45000000Hz output */
            break;
        case kClockModule_SIRC:
            CLOCK_SetClockDiv(kCLOCK_DivFRO_LF, 1U);       /* !< Set SYSCON.FROLFDIV divider to value 1 */
            CLOCK_SetupFRO12MClocking();                /*!< Setup FRO12M clock */
            break;
        case kClockModule_PLL:
            CLOCK_SetPLL1Freq(&pll1Setup);                       /*!< Configure PLL1 to the desired values */
            CLOCK_SetPll1MonitorMode(kSCG_Pll1MonitorDisable);            /* Pll1 Monitor is disabled */
            CLOCK_SetClockDiv(kCLOCK_DivPLL1CLK, 1U);      /* !< Set SYSCON.PLL1CLKDIV divider to value 1 */
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClockDiv(kCLOCK_DivAHBCLK, 1U);       /* !< Set SYSCON.AHBCLKDIV divider to value 1 */
            CLOCK_AttachClk(kFRO_HF_to_MAIN_CLK);/* !< Switch MAIN_CLK to kFRO_HF */
            break;
        case kClockModule_ADCClk:
            CLOCK_AttachClk(kNONE_to_ADC);                 /* !< Switch ADC to  */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);              /* !< Switch CLKOUT to  */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0);                /* !< Switch CMP0 to  */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1);                /* !< Switch CMP1 to  */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);             /* !< Switch CTIMER0 to  */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);             /* !< Switch CTIMER1 to  */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);             /* !< Switch CTIMER2 to  */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);             /* !< Switch CTIMER3 to  */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);             /* !< Switch CTIMER4 to  */
            break;
        case kClockModule_DAC0Clk:
            CLOCK_AttachClk(kNONE_to_DAC0);                /* !< Switch DAC0 to  */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);            /* !< Switch FLEXCAN0 to  */
            break;
        case kClockModule_FLEXIO0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXIO0);             /* !< Switch FLEXIO0 to  */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);            /* !< Switch I3C0FCLK to  */
            break;
        case kClockModule_LPI2C0Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C0);              /* !< Switch LPI2C0 to  */
            break;
        case kClockModule_LPI2C1Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C1);              /* !< Switch LPI2C1 to  */
            break;
        case kClockModule_LPI2C2Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C2);              /* !< Switch LPI2C2 to  */
            break;
        case kClockModule_LPI2C3Clk:
            CLOCK_AttachClk(kNONE_to_LPI2C3);              /* !< Switch LPI2C3 to  */
            break;
        case kClockModule_LPSPI0Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI0);              /* !< Switch LPSPI0 to  */
            break;
        case kClockModule_LPSPI1Clk:
            CLOCK_AttachClk(kNONE_to_LPSPI1);              /* !< Switch LPSPI1 to  */
            break;
        case kClockModule_LPTMR0Clk:
            CLOCK_AttachClk(kNONE_to_LPTMR0);              /* !< Switch LPTMR0 to  */
            break;
        case kClockModule_LPUART0Clk:
            CLOCK_AttachClk(kNONE_to_LPUART0);             /* !< Switch LPUART0 to  */
            break;
        case kClockModule_LPUART1Clk:
            CLOCK_AttachClk(kNONE_to_LPUART1);             /* !< Switch LPUART1 to  */
            break;
        case kClockModule_LPUART2Clk:
            CLOCK_AttachClk(kNONE_to_LPUART2);             /* !< Switch LPUART2 to  */
            break;
        case kClockModule_LPUART3Clk:
            CLOCK_AttachClk(kNONE_to_LPUART3);             /* !< Switch LPUART3 to  */
            break;
        case kClockModule_LPUART4Clk:
            CLOCK_AttachClk(kNONE_to_LPUART4);             /* !< Switch LPUART4 to  */
            break;
        case kClockModule_OSTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);             /* !< Switch OSTIMER to  */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kCPU_CLK_to_TRACE);            /* !< Switch TRACE to CPU_CLK */
            CLOCK_SetClockDiv(kCLOCK_DivTRACE, 1U);        /* !< Set MRCC.TRACE_CLKDIV divider to value 1 */
            break;
        case kClockModule_USB0ClkClk:
            CLOCK_AttachClk(kNONE_to_USB0);                /* !< Switch USB0 to  */
            break;
        case kClockModule_WWDT0Clk:
            CLOCK_SetClockDiv(kCLOCK_DivWWDT0, 1U);        /* !< Set MRCC.WWDT0_CLKDIV divider to value 1 */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            CLOCK_EnableClock(kCLOCK_InputMux);
            RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
            INPUTMUX0->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX0->FREQMEAS_TAR = INPUTMUX_FREQMEAS_TAR_INP(2);
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockPLL180M(void)
{
    uint32_t coreFreq;
    spc_active_mode_core_ldo_option_t ldoOption;
    spc_sram_voltage_config_t sramOption;

    /* Get the CPU Core frequency */
    coreFreq = CLOCK_GetCoreSysClkFreq();

    /* The flow of increasing voltage and frequency */
    if (coreFreq <= BOARD_BOOTCLOCKPLL180M_CORE_CLOCK) {
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
    }
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_PLL);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_SystemClk);

    /* The flow of decreasing voltage and frequency */
    if (coreFreq > BOARD_BOOTCLOCKPLL180M_CORE_CLOCK) {
        /* Configure Flash to support different voltage level and frequency */
        FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x1U));
        /* Specifies the operating voltage for the SRAM's read/write timing margin */
        sramOption.operateVoltage = kSPC_sramOperateAt1P2V;
        sramOption.requestVoltageUpdate =  true;
        (void)SPC_SetSRAMOperateVoltage(SPC0, &sramOption);
        /* Set the LDO_CORE VDD regulator level */
        ldoOption.CoreLDOVoltage = kSPC_CoreLDO_OverDriveVoltage;
        ldoOption.CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength;
        (void)SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOption);
    }

    BOARD_BootClockPLL180M_InitClockModule(kClockModule_ADCClk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_DAC0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_FLEXIO0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPI2C0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPI2C1Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPI2C2Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPI2C3Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPSPI0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPSPI1Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPTMR0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPUART0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPUART1Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPUART2Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPUART3Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_LPUART4Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_OSTIMER0Clk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_USB0ClkClk);
    BOARD_BootClockPLL180M_InitClockModule(kClockModule_WWDT0Clk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKPLL180M_CORE_CLOCK;
}
