/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXA176
package_id: MCXA176VLL
mcu_data: ksdk2_0
processor_version: 26.06.20
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 6576fcf0-725b-4cb8-8eca-6e744b74bee8
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - commonSetting:
    - HAL_GPIO_CONFLICT_CHECK_ENABLE: 'true'
    - HAL_GPIO_ISR_PRIORITY: '3'
    - HAL_GpioPreInit: 'true'
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma4'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'edma4_2.9.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - dmamux_devices: []
    - common_settings:
      - vars: []
      - enableHaltOnError: 'false'
      - enableDebugMode: 'false'
      - enableRoundRobinArbitration: 'fixedPriority'
      - enableGlobalChannelLink: 'true'
      - enableMasterIdReplication: 'false'
    - dma_table:
      - 0: []
      - 1: []
    - edma_channels:
      - 0:
        - apiMode: 'trans'
        - edma_channel:
          - channel_prefix_id: 'CH7'
          - uid: '1789096047450'
          - eDMAn: '7'
          - eDMA_source: 'kDma0RequestMuxCtimer4M0'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
          - masterIdReplicationEnable: 'noInit'
          - protectionLevel: 'noInit'
          - enable_custom_name: 'false'
        - resetChannel: 'true'
        - enableChannelRequest: 'true'
        - enableAsyncRequest: 'false'
        - enableAutoStop: 'true'
        - tcd_pool_enable: 'false'
        - tcd_settings:
          - tcd_size: '1'
          - tcd_memory_ptr_id: 'default'
        - transfer_config:
          - 0:
            - uid: '1789096515697'
            - tcdID: 'CH7_TRANSFER0'
            - ssize: 'kEDMA_TransferSize4Bytes'
            - saddr_expr: '&GPIO3->PDIR'
            - saddr_def: ''
            - soff: '0'
            - soff_def: ''
            - smod: 'kEDMA_ModuloDisable'
            - dsize: 'kEDMA_TransferSize4Bytes'
            - daddr_expr: 'g_gpio3SampleBuf'
            - daddr_def: 'extern volatile uint32_t g_gpio3SampleBuf[8];'
            - doff: 'sizeof(g_gpio3SampleBuf[0])'
            - doff_def: ''
            - dmod: 'kEDMA_ModuloDisable'
            - nbytes: '4'
            - MLconfig:
              - offsetType: 'disabled'
              - mloff: '0'
            - enableChannelLinkMinor: 'false'
            - linkedChannelMinor: '1789096047450'
            - citer: '8'
            - slast: '0'
            - dlast: '-32'
            - enableChannelLinkMajor: 'false'
            - linkedChannelMajor: '1789096047450'
            - submitTransfer: 'false'
        - loopTransfer: 'false'
        - no_init_uid: '1789096047484'
        - init_callback: 'true'
        - callback_function: 'GpioDmaFilterDmaCallback'
        - callback_user_data: ''
        - channel_enabled_interrupts: ''
        - interrupt_channel:
          - IRQn: 'DMA_CH7_IRQn'
          - enable_priority: 'true'
          - priority: '5'
      - 1:
        - apiMode: 'trans'
        - edma_channel:
          - channel_prefix_id: 'CH0'
          - uid: '1789190821978'
          - eDMAn: '0'
          - eDMA_source: 'dmaDisable'
          - init_channel_priority: 'false'
          - edma_channel_Preemption:
            - enableChannelPreemption: 'false'
            - enablePreemptAbility: 'false'
            - channelPriority: '0'
          - masterIdReplicationEnable: 'noInit'
          - protectionLevel: 'noInit'
          - enable_custom_name: 'false'
        - resetChannel: 'true'
        - enableChannelRequest: 'false'
        - enableAsyncRequest: 'false'
        - enableAutoStop: 'true'
        - tcd_pool_enable: 'false'
        - tcd_settings:
          - tcd_size: '1'
          - tcd_memory_ptr_id: 'default'
        - transfer_config: []
        - loopTransfer: 'false'
        - no_init_uid: '1789190821989'
        - init_callback: 'true'
        - callback_function: 'RS485_DmaCallback'
        - callback_user_data: ''
        - channel_enabled_interrupts: ''
        - interrupt_channel:
          - IRQn: 'DMA_CH0_IRQn'
          - enable_priority: 'true'
          - priority: '5'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
edma_config_t DMA0_config = {
  .enableMasterIdReplication = false,
  .enableGlobalChannelLink = true,
  .enableHaltOnError = false,
  .enableDebugMode = false,
  .enableRoundRobinArbitration = false
};
/* Tansactional transfer configurations */
edma_transfer_config_t DMA0_CH7_Transfers_config[1];
edma_handle_t DMA0_CH7_Handle;
edma_handle_t DMA0_CH0_Handle;

static void DMA0_init(void) {

  /* Channel CH7 initialization */
  /* Set the kDma0RequestMuxCtimer4M0 request */
  EDMA_SetChannelMux(DMA0_DMA_BASEADDR, DMA0_CH7_DMA_CHANNEL, DMA0_CH7_DMA_REQUEST);
  /* Create the eDMA DMA0_CH7_Handle handle */
  EDMA_CreateHandle(&DMA0_CH7_Handle, DMA0_DMA_BASEADDR, DMA0_CH7_DMA_CHANNEL);
  /* DMA0 channel 7 reset */
  EDMA_ResetChannel(DMA0_DMA_BASEADDR, DMA0_CH7_DMA_CHANNEL);
  /* DMA callback initialization */
  EDMA_SetCallback(&DMA0_CH7_Handle, GpioDmaFilterDmaCallback, NULL);
  /* Interrupt vector DMA_CH7_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(DMA0_DMA_CH_INT_DONE_7_IRQN, DMA0_DMA_CH_INT_DONE_7_IRQ_PRIORITY);
  /* DMA0 transfer CH7_TRANSFER0 configuration */
  EDMA_PrepareTransferConfig(&DMA0_CH7_TRANSFER0_CONFIG, (void *) &GPIO3->PDIR, 1 << kEDMA_TransferSize4Bytes, 0, (void *) g_gpio3SampleBuf, 1 << kEDMA_TransferSize4Bytes, sizeof(g_gpio3SampleBuf[0]), 4U, 32U); 
  DMA0_CH7_TRANSFER0_CONFIG.dstMajorLoopOffset = -32;

  /* Channel CH0 initialization */
  /* Create the eDMA DMA0_CH0_Handle handle */
  EDMA_CreateHandle(&DMA0_CH0_Handle, DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* DMA0 channel 0 reset */
  EDMA_ResetChannel(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* DMA callback initialization */
  EDMA_SetCallback(&DMA0_CH0_Handle, RS485_DmaCallback, NULL);
  /* Interrupt vector DMA_CH0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(DMA0_DMA_CH_INT_DONE_0_IRQN, DMA0_DMA_CH_INT_DONE_0_IRQ_PRIORITY);
  /* DMA0 hardware channel 7 request auto stop */
  EDMA_EnableAutoStopRequest(DMA0_DMA_BASEADDR, DMA0_CH7_DMA_CHANNEL, true);
  /* DMA0 channel 7 peripheral request */
  EDMA_EnableChannelRequest(DMA0_DMA_BASEADDR, DMA0_CH7_DMA_CHANNEL);
  /* DMA0 hardware channel 0 request auto stop */
  EDMA_EnableAutoStopRequest(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL, true);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
      - 2: []
    - interrupts:
      - 0:
        - channelId: 'LPUART0_NVIC'
        - interrupt_t:
          - IRQn: 'LPUART0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '5'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO0'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO0'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level){
  hal_gpio_pin_config_t temp;
  /* Array of GPIO peripheral base address. */
  static GPIO_Type *const s_gpioBases[] = GPIO_BASE_PTRS;
  uint8_t portInd;
  /* Find the port index from base address mappings. */
  for (portInd = 0U; portInd < ARRAY_SIZE(s_gpioBases); portInd++)
  {    if (s_gpioBases[portInd] == port)
    {
      break;
    }
  }
  
  assert(portInd < ARRAY_SIZE(s_gpioBases));
  
  temp.direction = direction;
  temp.level = level;
  temp.port = portInd;
  temp.pin = pin;
  
  return temp;
};
GPIO_HANDLE_DEFINE(BOARD_INITPINS_RS485_EN_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_EN_15V_handle);

static void GPIO0_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* GPIO, 19 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_RS485_EN_GPIO, BOARD_INITPINS_RS485_EN_PIN, BOARD_INITPINS_RS485_EN_PIN_DIRECTION, BOARD_INITPINS_RS485_EN_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_RS485_EN_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 23 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_EN_15V_GPIO, BOARD_INITPINS_EN_15V_PIN, BOARD_INITPINS_EN_15V_PIN_DIRECTION, BOARD_INITPINS_EN_15V_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_EN_15V_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
    - gpioPinsOverView:
      - 0: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
GPIO_HANDLE_DEFINE(BOARD_INITPINS_LED_handle);

static void GPIO1_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* GPIO, 8 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_LED_GPIO, BOARD_INITPINS_LED_PIN, BOARD_INITPINS_LED_PIN_DIRECTION, BOARD_INITPINS_LED_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_LED_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * GPIO2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO2'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO2'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
      - 2: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
      - 2: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IO7_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_ADC_PWR_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IN4_handle);

static void GPIO2_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* GPIO, 20 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IO7_GPIO, BOARD_INITPINS_IO7_PIN, BOARD_INITPINS_IO7_PIN_DIRECTION, BOARD_INITPINS_IO7_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IO7_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 21 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_ADC_PWR_GPIO, BOARD_INITPINS_ADC_PWR_PIN, BOARD_INITPINS_ADC_PWR_PIN_DIRECTION, BOARD_INITPINS_ADC_PWR_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_ADC_PWR_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 23 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IN4_GPIO, BOARD_INITPINS_IN4_PIN, BOARD_INITPINS_IN4_PIN_DIRECTION, BOARD_INITPINS_IN4_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IN4_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * GPIO3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO3'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO3'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
GPIO_HANDLE_DEFINE(BOARD_INITPINS_RESET_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_LED_OUT_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IO2_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_RS485_EN2_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IN5_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IN1_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IN10_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IN6_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IN7_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_I2C3_WP_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IO3_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_IO1_handle);

static void GPIO3_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* GPIO, 11 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_RESET_GPIO, BOARD_INITPINS_RESET_PIN, BOARD_INITPINS_RESET_PIN_DIRECTION, BOARD_INITPINS_RESET_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_RESET_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 12 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_LED_OUT_GPIO, BOARD_INITPINS_LED_OUT_PIN, BOARD_INITPINS_LED_OUT_PIN_DIRECTION, BOARD_INITPINS_LED_OUT_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_LED_OUT_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 13 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IO2_GPIO, BOARD_INITPINS_IO2_PIN, BOARD_INITPINS_IO2_PIN_DIRECTION, BOARD_INITPINS_IO2_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IO2_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 16 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_RS485_EN2_GPIO, BOARD_INITPINS_RS485_EN2_PIN, BOARD_INITPINS_RS485_EN2_PIN_DIRECTION, BOARD_INITPINS_RS485_EN2_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_RS485_EN2_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 17 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IN5_GPIO, BOARD_INITPINS_IN5_PIN, BOARD_INITPINS_IN5_PIN_DIRECTION, BOARD_INITPINS_IN5_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IN5_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 18 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IN1_GPIO, BOARD_INITPINS_IN1_PIN, BOARD_INITPINS_IN1_PIN_DIRECTION, BOARD_INITPINS_IN1_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IN1_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 19 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IN10_GPIO, BOARD_INITPINS_IN10_PIN, BOARD_INITPINS_IN10_PIN_DIRECTION, BOARD_INITPINS_IN10_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IN10_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 20 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IN6_GPIO, BOARD_INITPINS_IN6_PIN, BOARD_INITPINS_IN6_PIN_DIRECTION, BOARD_INITPINS_IN6_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IN6_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 21 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IN7_GPIO, BOARD_INITPINS_IN7_PIN, BOARD_INITPINS_IN7_PIN_DIRECTION, BOARD_INITPINS_IN7_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IN7_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 22 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_I2C3_WP_GPIO, BOARD_INITPINS_I2C3_WP_PIN, BOARD_INITPINS_I2C3_WP_PIN_DIRECTION, BOARD_INITPINS_I2C3_WP_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_I2C3_WP_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 29 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IO3_GPIO, BOARD_INITPINS_IO3_PIN, BOARD_INITPINS_IO3_PIN_DIRECTION, BOARD_INITPINS_IO3_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IO3_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* GPIO, 30 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_IO1_GPIO, BOARD_INITPINS_IO1_PIN, BOARD_INITPINS_IO1_PIN_DIRECTION, BOARD_INITPINS_IO1_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_IO1_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * GPIO4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO4'
- type: 'gpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'gpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO4'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters: []
    - gpioPinsOverView: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void GPIO4_init(void) {
  /* GPIO adapter initialization */
}

/***********************************************************************************************************************
 * CRC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CRC0'
- type: 'crc'
- mode: 'General'
- custom_name_enabled: 'false'
- type_id: 'crc_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CRC0'
- config_sets:
  - fsl_crc:
    - config:
      - polynomial: '0x04C11DB7'
      - seed: '0xFFFFFFFF'
      - reflectIn: 'true'
      - reflectOut: 'true'
      - complementChecksum: 'false'
      - crcBits: 'kCrcBits32'
      - crcResult: 'kCrcFinalChecksum'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const crc_config_t CRC0_config = {
  .polynomial = 0x4C11DB7UL,
  .seed = 0xFFFFFFFFUL,
  .reflectIn = true,
  .reflectOut = true,
  .complementChecksum = false,
  .crcBits = kCrcBits32,
  .crcResult = kCrcFinalChecksum
};

static void CRC0_init(void) {
  CRC_Init(CRC0_PERIPHERAL, &CRC0_config);
}

/***********************************************************************************************************************
 * CTIMER4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER4'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_2.2.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER4'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - timerPrescaler: '180'
    - EnableTimerInInit: 'false'
    - matchChannels:
      - 0:
        - matchChannelPrefixId: 'Match_0'
        - matchChannel: 'kCTIMER_Match_0'
        - matchValueStr: '100'
        - enableCounterReset: 'true'
        - enableCounterStop: 'false'
        - outControl: 'kCTIMER_Output_NoAction'
        - outPinInitValue: 'low'
        - enableInterrupt: 'false'
    - captureChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER4_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER4_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 179
};
const ctimer_match_config_t CTIMER4_Match_0_config = {
  .matchValue = 99,
  .enableCounterReset = true,
  .enableCounterStop = false,
  .outControl = kCTIMER_Output_NoAction,
  .outPinInitState = false,
  .enableInterrupt = false
};

static void CTIMER4_init(void) {
  /* CTIMER4 peripheral initialization */
  CTIMER_Init(CTIMER4_PERIPHERAL, &CTIMER4_config);
  /* Match channel 0 of CTIMER4 peripheral initialization */
  CTIMER_SetupMatch(CTIMER4_PERIPHERAL, CTIMER4_MATCH_0_CHANNEL, &CTIMER4_Match_0_config);
}

/***********************************************************************************************************************
 * RTC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'RTC0'
- type: 'rtc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'rtc_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'RTC0'
- config_sets:
  - fsl_rtc:
    - clockConfig_t:
      - clockSource: 'clk_16khz'
      - clockSourceFreq: 'BOARD_BootClockFROHF180M'
    - rtc_config:
      - updateMode: 'false'
      - supervisorAccess: 'false'
      - compensationIntervalInt: '1'
      - compensationTimeInt: '0'
      - setDateTime: 'true'
      - rtc_datetime:
        - year: '2000'
        - month: '1'
        - day: '1'
        - hour: '0'
        - minute: '0'
        - second: '0'
      - setAlarm: 'false'
      - alarm_datetime:
        - year: '1970'
        - month: '1'
        - day: '1'
        - hour: '0'
        - minute: '0'
        - second: '0'
      - start: 'true'
    - interruptsCfg:
      - interruptSources: ''
      - isSecondsInterruptEnabled: 'false'
      - secondsInterrupt:
        - IRQn: 'RTC_1HZ_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '1'
        - enable_custom_name: 'false'
      - isInterruptEnabled: 'false'
      - commonInterrupt:
        - IRQn: 'RTC_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const rtc_config_t RTC0_config = {
  .wakeupSelect = false,
  .updateMode = false,
  .supervisorAccess = false,
  .compensationInterval = 0x0U,
  .compensationTime = 0x0U
};
rtc_datetime_t RTC0_dateTimeStruct = {
  .year = 2000U,
  .month = 1U,
  .day = 1U,
  .hour = 0U,
  .minute = 0U,
  .second = 0U
};

static void RTC0_init(void) {
  /* RTC initialization */
  RTC_Init(RTC0_PERIPHERAL, &RTC0_config);
  /* Set LPO 16kHz clock source */
  RTC_EnableLPOClock(RTC0_PERIPHERAL, true);
  /* Stop RTC timer */
  RTC_StopTimer(RTC0_PERIPHERAL);
  /* Date and time initialization */
  RTC_SetDatetime(RTC0_PERIPHERAL, &RTC0_dateTimeStruct);
  /* Start RTC timer */
  RTC_StartTimer(RTC0_PERIPHERAL);
}

/***********************************************************************************************************************
 * DAC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DAC0'
- type: 'dac_1'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'dac_1_2.1.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DAC0'
- config_sets:
  - fsl_dac:
    - dac_config:
      - fifoWatermarkLevel: '0'
      - fifoTriggerMode: 'kDAC_FIFOTriggerBySoftwareMode'
      - fifoWorkMode: 'kDAC_FIFODisabled'
      - referenceVoltageSource: 'kDAC_ReferenceVoltageSourceAlt1'
      - referenceCurrentSource: 'kDAC_ReferenceCurrentSourcePtat'
      - enableOpampBuffer: 'true'
      - periodicTriggerNumber: '0'
      - periodicTriggerWidth: '0'
      - syncTime: '0'
      - enableLowerLowPowerMode: 'false'
    - enable_dma: 'false'
    - dac_dma: 'kDAC_FIFOEmptyDMAEnable'
    - enable_DAC: 'true'
    - enable_convert: 'true'
    - convert_value: '0'
    - interrupt_config:
      - dac_interrupts: ''
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'DAC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dac_config_t DAC0_config = {
  .fifoWatermarkLevel = 0UL,
  .fifoTriggerMode = kDAC_FIFOTriggerBySoftwareMode,
  .fifoWorkMode = kDAC_FIFODisabled,
  .referenceVoltageSource = kDAC_ReferenceVoltageSourceAlt1,
  .referenceCurrentSource = kDAC_ReferenceCurrentSourcePtat,
  .enableOpampBuffer = true,
  .periodicTriggerNumber = 0UL,
  .periodicTriggerWidth = 0UL,
  .syncTime = 0UL,
  .enableLowerLowPowerMode = false,
};

static void DAC0_init(void) {
  /* Power up analog module in SPC */
  SPC_EnableActiveModeAnalogModules(SPC0, kSPC_controlDac0);
  /* Initialize the LPDAC */
  DAC_Init(DAC0_PERIPHERAL, &DAC0_config);
  /* Enable the LPDAC */
  DAC_Enable(DAC0_PERIPHERAL, true);
  /* Set LPDAC value */
  DAC_SetData(DAC0_PERIPHERAL, 0);
}

/***********************************************************************************************************************
 * LPSPI0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI0'
- type: 'lpspi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpspi_2.6.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI0'
- config_sets:
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master:
      - baudRate: '20000000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '400'
      - lastSckToPcsDelayInNanoSec: '400'
      - betweenTransferDelayInNanoSec: '100'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - pcsFunc: 'kLPSPI_PcsAsCs'
      - dataOutConfig: 'kLpspiDataOutRetained'
      - enableInputDelay: 'false'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - allPcsPolarityEnable: 'false'
    - allPcsPolarity:
      - kLPSPI_Pcs1Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs2Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs3Active: 'kLPSPI_PcsActiveLow'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI0_config = {
  .baudRate = 20000000UL,
  .bitsPerFrame = 8UL,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 400UL,
  .lastSckToPcsDelayInNanoSec = 400UL,
  .betweenTransferDelayInNanoSec = 100UL,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .pcsFunc = kLPSPI_PcsAsCs,
  .dataOutConfig = kLpspiDataOutRetained,
  .enableInputDelay = false
};

static void LPSPI0_init(void) {
  LPSPI_MasterInit(LPSPI0_PERIPHERAL, &LPSPI0_config, LPSPI0_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * LPSPI1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI1'
- type: 'lpspi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpspi_2.6.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI1'
- config_sets:
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master:
      - baudRate: '20000000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '400'
      - lastSckToPcsDelayInNanoSec: '400'
      - betweenTransferDelayInNanoSec: '100'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - pcsFunc: 'kLPSPI_PcsAsCs'
      - dataOutConfig: 'kLpspiDataOutRetained'
      - enableInputDelay: 'false'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - allPcsPolarityEnable: 'false'
    - allPcsPolarity:
      - kLPSPI_Pcs1Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs2Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs3Active: 'kLPSPI_PcsActiveLow'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI1_config = {
  .baudRate = 20000000UL,
  .bitsPerFrame = 8UL,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 400UL,
  .lastSckToPcsDelayInNanoSec = 400UL,
  .betweenTransferDelayInNanoSec = 100UL,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .pcsFunc = kLPSPI_PcsAsCs,
  .dataOutConfig = kLpspiDataOutRetained,
  .enableInputDelay = false
};

static void LPSPI1_init(void) {
  LPSPI_MasterInit(LPSPI1_PERIPHERAL, &LPSPI1_config, LPSPI1_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * LPUART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART0'
- type: 'lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpuart_2.11.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART0'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - txRtsPolarity: 'kLPUART_RtsPolarityLow'
      - rtsWatermark: '0'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter4'
      - enableTx: 'true'
      - enableRx: 'true'
      - swapTxdRxd: 'false'
      - inverseTxd: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART0_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .txRtsPolarity = kLPUART_RtsPolarityLow,
  .rtsWatermark = 0U,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter4,
  .enableTx = true,
  .enableRx = true,
  .swapTxdRxd = false,
  .inverseTxd = false
};

static void LPUART0_init(void) {
  LPUART_Init(LPUART0_PERIPHERAL, &LPUART0_config, LPUART0_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Interrupt vector LPUART0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(LPUART0_NVIC_IRQN, LPUART0_NVIC_IRQ_PRIORITY);
  /* Enable interrupt LPUART0_NVIC_IRQN request in the NVIC */
  EnableIRQ(LPUART0_NVIC_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  (void)memset(DMA0_config.channelConfig, 0, FSL_FEATURE_EDMA_INSTANCE_CHANNELn(DMA0_DMA_BASEADDR) * sizeof(edma_channel_config_t *));
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);
  /* GPIO adapter pre-initialization */
  HAL_GpioPreInit();

  /* Initialize components */
  DMA0_init();
  GPIO0_init();
  GPIO1_init();
  GPIO2_init();
  GPIO3_init();
  GPIO4_init();
  CRC0_init();
  CTIMER4_init();
  RTC0_init();
  DAC0_init();
  LPSPI0_init();
  LPSPI1_init();
  LPUART0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
