/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PCR_PS_ps1 0x01u            /*!<@brief Pull Select: Enables internal pullup resistor */
#define PORT0_PCR0_MUX_mux01 0x01u  /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT0_PCR1_MUX_mux01 0x01u  /*!<@brief Pin Multiplex Control: Alternative 1 (chip-specific) */
#define PORT2_PCR17_MUX_mux10 0x02u /*!<@brief Pin Multiplex Control: Alternative 2 (chip-specific) */
#define PORT2_PCR20_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR21_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR23_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT0_1 (number 77), SWCLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SWCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SWCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SWCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT0_0 (number 76), SWDIO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT1_8 (number 1), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_GPIO_PIN 8U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORT3_16 (number 59), RS485_EN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RS485_EN2_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RS485_EN2_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS485_EN2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN2_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS485_EN2_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_21 (number 41), ADC_PWR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_PWR_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_PWR_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_ADC_PWR_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ADC_PWR_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_PWR_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_PWR_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_PWR_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_20 (number 40), IO7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO7_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IO7_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_IO7_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IO7_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IO7_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IO7_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IO7_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_13 (number 62), IO2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO2_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IO2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_IO2_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IO2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IO2_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IO2_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IO2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_12 (number 63), LED_OUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_OUT_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_OUT_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_OUT_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_OUT_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_OUT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_OUT_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_OUT_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_11 (number 66), RESET
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RESET_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RESET_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RESET_GPIO_PIN 11U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RESET_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RESET_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RESET_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RESET_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_22 (number 53), I2C3_WP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_I2C3_WP_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_I2C3_WP_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_I2C3_WP_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_I2C3_WP_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_WP_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_WP_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_WP_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_23 (number 42), IN4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN4_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN4_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN4_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN4_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN4_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN4_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_12 (number 34), SPI1_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI1_SCK_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI1_SCK_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI1_SCK_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT2_13 (number 35), SPI1_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI1_MOSI_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI1_MOSI_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI1_MOSI_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_17 (number 38), SPI1_CS
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI1_CS_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI1_CS_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI1_CS_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_0 (number 91), SPI0_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_MOSI_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_MOSI_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_MOSI_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_1 (number 92), SPI0_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_SCK_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_SCK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_SCK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_2 (number 93), SPI0_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_MISO_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_MISO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_MISO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_3 (number 94), SPI0_CS
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SPI0_CS_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SPI0_CS_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SPI0_CS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_12 (number 5), I2C1_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C1_SDA_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C1_SDA_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C1_SDA_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT1_13 (number 6), I2C1_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C1_SCL_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C1_SCL_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C1_SCL_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_27 (number 52), I2C3_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_SCL_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_SCL_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_SCL_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_29 (number 50), IO3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO3_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IO3_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_IO3_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IO3_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IO3_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IO3_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IO3_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_30 (number 49), IO1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IO1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IO1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_IO1_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IO1_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IO1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IO1_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IO1_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_28 (number 51), I2C3_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I2C3_SDA_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I2C3_SDA_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I2C3_SDA_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_23 (number 90), EN_15V
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EN_15V_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EN_15V_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_EN_15V_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_EN_15V_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_EN_15V_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EN_15V_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_EN_15V_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_31 (number 11), OSC_IN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OSC_IN_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OSC_IN_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OSC_IN_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_30 (number 10), OSC_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OSC_OUT_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OSC_OUT_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OSC_OUT_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_17 (number 58), IN5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN5_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN5_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN5_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN5_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN5_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN5_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_18 (number 57), IN1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN1_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN1_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN1_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN1_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN1_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN1_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_19 (number 56), IN10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN10_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN10_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN10_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN10_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN10_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN10_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT3_20 (number 55), IN6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN6_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN6_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN6_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN6_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN6_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN6_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_21 (number 54), IN7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_IN7_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_IN7_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_IN7_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_IN7_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_IN7_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_IN7_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT2_2 (number 24), DAC1_1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DAC1_1_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DAC1_1_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DAC1_1_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT0_20 (number 87), UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART0_RX_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART0_RX_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART0_RX_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_21 (number 88), UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART0_TX_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART0_TX_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART0_TX_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_19 (number 86), RS485_EN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS485_EN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RS485_EN_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RS485_EN_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RS485_EN_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS485_EN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS485_EN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS485_EN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_8 (number 69), UART1_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART1_RX_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART1_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART1_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_9 (number 68), UART1_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_UART1_TX_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_UART1_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_UART1_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_0 (number 73), PWM0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWM0_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWM0_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWM0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
