/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MCXA176
package_id: MCXA176VLL
mcu_data: ksdk2_0
processor_version: 26.06.20
external_user_signals: {}
pin_labels:
- {pin_num: '1', pin_signal: P1_8/WUU0_IN10/FREQME_CLK_IN0/LPUART1_RXD/LPI2C2_SDA/CT_INP8/CT0_MAT2/FLEXIO0_D16/SmartDMA_PIO4/I3C0_SDA, label: LED, identifier: LED}
- {pin_num: '59', pin_signal: P3_16/LPUART4_RTS_B/CT_INP8/FLEXIO0_D24/PWM1_A0/SmartDMA_PIO16, label: RS485_EN2, identifier: RS485_EN2}
- {pin_num: '41', pin_signal: P2_21/TRIG_IN9/LPSPI1_PCS3/CT2_MAT1/FLEXIO0_D29/SmartDMA_PIO23, label: ADC_PWR, identifier: ADC_PWR}
- {pin_num: '40', pin_signal: P2_20/TRIG_IN8/LPSPI1_PCS2/CT2_MAT0/FLEXIO0_D28/SmartDMA_PIO22, label: IO7, identifier: IO7}
- {pin_num: '50', pin_signal: P3_29/WUU0_IN27/TAMPER1/LPI2C3_HREQ/CT_INP3/CT3_MAT3/FLEXIO0_D29/SmartDMA_PIO29/ADC1_A22, label: IO3, identifier: IO1;IO3}
- {pin_num: '62', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/FLEXIO0_D21/PWM1_B2/SmartDMA_PIO13, label: IO2, identifier: IO2}
- {pin_num: '51', pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28/PWM1_B3/SmartDMA_PIO28, label: I2C3_SDA, identifier: IO3;I2C3_SDA}
- {pin_num: '63', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/FLEXIO0_D20/PWM1_A2/SmartDMA_PIO12, label: LED_OUT, identifier: LED_OUT}
- {pin_num: '66', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/FLEXIO0_D19/SmartDMA_PIO11, label: RESET, identifier: RESET}
- {pin_num: '58', pin_signal: P3_17/LPUART4_CTS_B/CT_INP9/FLEXIO0_D25/PWM1_B0/SmartDMA_PIO17, label: IN5, identifier: IN5}
- {pin_num: '57', pin_signal: P3_18/TAMPER5/LPUART4_RXD/CT2_MAT0/PWM0_X0/FLEXIO0_D26/PWM1_X0/SmartDMA_PIO18, label: IN1, identifier: IN1}
- {pin_num: '90', pin_signal: P0_23/WUU0_IN5/LPUART0_CTS_B/CT_INP3/CT0_MAT1/FLEXIO0_D7/SmartDMA_PIO13/ADC0_A13, label: EN_15V, identifier: EN_15V}
- {pin_num: '53', pin_signal: P3_22/LPUART1_RTS_B/CT_INP10/FLEXIO0_D30/PWM1_X2/SmartDMA_PIO22, label: I2C3_WP, identifier: I2C3_WP}
- {pin_num: '54', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/PWM0_X3/FLEXIO0_D29/PWM1_B3/SmartDMA_PIO21, label: IN7, identifier: IN7}
- {pin_num: '56', pin_signal: P3_19/TAMPER4/LPUART4_TXD/CT2_MAT1/PWM0_X1/FLEXIO0_D27/PWM1_X1/SmartDMA_PIO19, label: IN10, identifier: IN10}
- {pin_num: '55', pin_signal: P3_20/TRIG_OUT0/LPI2C3_SDA/LPUART1_RXD/CT2_MAT2/PWM0_X2/FLEXIO0_D28/PWM1_A3/SmartDMA_PIO20, label: IN6, identifier: IN6}
- {pin_num: '76', pin_signal: P0_0/TMS/SWDIO/LPUART0_RTS_B/LPSPI0_PCS0/CT_INP0/FLEXIO0_D0, label: SWDIO, identifier: SWDIO}
- {pin_num: '77', pin_signal: P0_1/TCLK/SWCLK/LPUART0_CTS_B/LPSPI0_SDI/CT_INP1/FLEXIO0_D1, label: SWCLK, identifier: SWCLK}
- {pin_num: '42', pin_signal: P2_23/TRIG_OUT5/CT2_MAT3/FLEXIO0_D31, label: IN4, identifier: IN4}
- {pin_num: '2', pin_signal: P1_9/FREQME_CLK_IN1/LPUART1_TXD/LPI2C2_SCL/CT_INP9/CT0_MAT3/FLEXIO0_D17/SmartDMA_PIO5/I3C0_SCL, label: ALM_IN_1, identifier: ALM_IN_1}
- {pin_num: '34', pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/FLEXIO0_D20/SmartDMA_PIO16/CAN0_RXD/ADC0_A5/OPAMP0_INP, label: SPI1_SCK,
  identifier: SPI1;SPI1_SCK}
- {pin_num: '35', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/FLEXIO0_D21/SmartDMA_PIO17/CAN0_TXD/ADC1_A5/OPAMP0_INN, label: SPI1_MOSI, identifier: SPI_MOSI;SPI1_MOSI}
- {pin_num: '38', pin_signal: P2_17/TRIG_IN9/LPSPI1_PCS0/LPUART1_CTS_B/CT3_MAT1/CT0_MAT3/FLEXIO0_D25/SmartDMA_PIO20/ADC1_A6, label: SPI1_CS, identifier: SPI1_CS}
- {pin_num: '92', pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/FLEXIO0_D9/ADC0_A17/CMP1_IN3, label: SPI0_SCK, identifier: SPI0_SCK}
- {pin_num: '94', pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11/CAN0_RXD/ADC0_A19/CMP0_IN1, label: SPI0_CS, identifier: SPI_MOSI;SPI0_MOSI;SPI0_CS}
- {pin_num: '93', pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/FLEXIO0_D10/CAN0_TXD/ADC0_A18, label: SPI0_MISO, identifier: SPI0_MISO}
- {pin_num: '91', pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/FLEXIO0_D8/ADC0_A16/CMP0_IN3, label: SPI0_MOSI, identifier: SPI0_MOSI}
- {pin_num: '5', pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/FLEXIO0_D20/SmartDMA_PIO8/ADC1_A10, label: I2C1_SDA, identifier: I2C1_SDA}
- {pin_num: '6', pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/FLEXIO0_D21/SmartDMA_PIO9/ADC1_A11, label: I2C1_SCL, identifier: I2C1_SCK;I2C1_SCL}
- {pin_num: '49', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/FLEXIO0_D30/PWM1_A0/SmartDMA_PIO30/ADC1_A21, label: IO1, identifier: IO1}
- {pin_num: '52', pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/FLEXIO0_D27/PWM1_A3/SmartDMA_PIO27, label: I2C3_SCL, identifier: I2C3_SCL}
- {pin_num: '11', pin_signal: P1_31/TRIG_IN4/LPI2C0_SCL/CT_INP17/FLEXIO0_D31/I3C0_SCL/EXTAL48M, label: OSC_IN, identifier: OSC_IN}
- {pin_num: '10', pin_signal: P1_30/TRIG_OUT3/LPI2C0_SDA/CT_INP16/FLEXIO0_D30/I3C0_SDA/XTAL48M, label: OSC_OUT, identifier: OSC_OUT}
- {pin_num: '24', pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT, label: DAC1_1, identifier: DAC1_1}
- {pin_num: '87', pin_signal: P0_20/WUU0_IN4/LPUART0_RXD/CT_INP0/FLEXIO0_D4/SmartDMA_PIO10/ADC0_A10, label: UART0_RX, identifier: UART0_RX}
- {pin_num: '88', pin_signal: P0_21/LPUART0_TXD/CT_INP1/FLEXIO0_D5/SmartDMA_PIO11/ADC0_A11, label: UART0_TX, identifier: UART0_TX}
- {pin_num: '86', pin_signal: P0_19/WUU0_IN3/LPI2C0_SDAS/CT0_MAT3/FLEXIO0_D3/SmartDMA_PIO9/CMP1_OUT/ADC0_A9, label: RS485_EN, identifier: RS485_EN}
- {pin_num: '69', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/FLEXIO0_D16/SmartDMA_PIO8/CLKOUT, label: UART1_RX, identifier: UART1_RX}
- {pin_num: '68', pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/FLEXIO0_D17/SmartDMA_PIO9, label: UART1_TX, identifier: UART1_TX}
- {pin_num: '73', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/FLEXIO0_D8/PWM1_X0/SmartDMA_PIO0, label: PWM0, identifier: PWM1;PWM0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '77', peripheral: SWD, signal: SWCLK, pin_signal: P0_1/TCLK/SWCLK/LPUART0_CTS_B/LPSPI0_SDI/CT_INP1/FLEXIO0_D1}
  - {pin_num: '76', peripheral: SWD, signal: SWDIO, pin_signal: P0_0/TMS/SWDIO/LPUART0_RTS_B/LPSPI0_PCS0/CT_INP0/FLEXIO0_D0}
  - {pin_num: '1', peripheral: GPIO1, signal: 'GPIO, 8', pin_signal: P1_8/WUU0_IN10/FREQME_CLK_IN0/LPUART1_RXD/LPI2C2_SDA/CT_INP8/CT0_MAT2/FLEXIO0_D16/SmartDMA_PIO4/I3C0_SDA,
    direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '59', peripheral: GPIO3, signal: 'GPIO, 16', pin_signal: P3_16/LPUART4_RTS_B/CT_INP8/FLEXIO0_D24/PWM1_A0/SmartDMA_PIO16, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '41', peripheral: GPIO2, signal: 'GPIO, 21', pin_signal: P2_21/TRIG_IN9/LPSPI1_PCS3/CT2_MAT1/FLEXIO0_D29/SmartDMA_PIO23, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '40', peripheral: GPIO2, signal: 'GPIO, 20', pin_signal: P2_20/TRIG_IN8/LPSPI1_PCS2/CT2_MAT0/FLEXIO0_D28/SmartDMA_PIO22, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '62', peripheral: GPIO3, signal: 'GPIO, 13', pin_signal: P3_13/LPUART2_CTS_B/LPUART3_RXD/CT1_MAT3/PWM0_X1/FLEXIO0_D21/PWM1_B2/SmartDMA_PIO13, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: '63', peripheral: GPIO3, signal: 'GPIO, 12', pin_signal: P3_12/LPUART2_RTS_B/LPUART3_TXD/CT1_MAT2/PWM0_X0/FLEXIO0_D20/PWM1_A2/SmartDMA_PIO12, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: '66', peripheral: GPIO3, signal: 'GPIO, 11', pin_signal: P3_11/WUU0_IN24/TRIG_IN6/LPSPI1_PCS0/LPUART1_CTS_B/CT1_MAT1/PWM0_B2/FLEXIO0_D19/SmartDMA_PIO11,
    direction: OUTPUT}
  - {pin_num: '53', peripheral: GPIO3, signal: 'GPIO, 22', pin_signal: P3_22/LPUART1_RTS_B/CT_INP10/FLEXIO0_D30/PWM1_X2/SmartDMA_PIO22, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '42', peripheral: GPIO2, signal: 'GPIO, 23', pin_signal: P2_23/TRIG_OUT5/CT2_MAT3/FLEXIO0_D31, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptStatusFlagDisabled,
    pull_select: up}
  - {pin_num: '34', peripheral: LPSPI1, signal: SCK, pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT4_MAT0/CT0_MAT0/FLEXIO0_D20/SmartDMA_PIO16/CAN0_RXD/ADC0_A5/OPAMP0_INP,
    identifier: SPI1_SCK}
  - {pin_num: '35', peripheral: LPSPI1, signal: OUT, pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT4_MAT1/CT0_MAT1/FLEXIO0_D21/SmartDMA_PIO17/CAN0_TXD/ADC1_A5/OPAMP0_INN,
    identifier: SPI1_MOSI}
  - {pin_num: '38', peripheral: LPSPI1, signal: PCS0, pin_signal: P2_17/TRIG_IN9/LPSPI1_PCS0/LPUART1_CTS_B/CT3_MAT1/CT0_MAT3/FLEXIO0_D25/SmartDMA_PIO20/ADC1_A6}
  - {pin_num: '91', peripheral: LPSPI0, signal: OUT, pin_signal: P1_0/WUU0_IN6/LPTMR0_ALT3/TRIG_IN0/LPSPI0_SDO/LPI2C1_SDA/CT_INP4/CT0_MAT2/FLEXIO0_D8/ADC0_A16/CMP0_IN3}
  - {pin_num: '92', peripheral: LPSPI0, signal: SCK, pin_signal: P1_1/TRIG_IN1/LPSPI0_SCK/LPI2C1_SCL/CT_INP5/CT0_MAT3/FLEXIO0_D9/ADC0_A17/CMP1_IN3}
  - {pin_num: '93', peripheral: LPSPI0, signal: IN, pin_signal: P1_2/TRIG_OUT0/LPSPI0_SDI/LPI2C1_SDAS/CT1_MAT0/CT_INP0/FLEXIO0_D10/CAN0_TXD/ADC0_A18}
  - {pin_num: '94', peripheral: LPSPI0, signal: PCS0, pin_signal: P1_3/WUU0_IN7/TRIG_OUT1/LPSPI0_PCS0/LPI2C1_SCLS/CT1_MAT1/CT_INP1/FLEXIO0_D11/CAN0_RXD/ADC0_A19/CMP0_IN1,
    identifier: SPI0_CS}
  - {pin_num: '5', peripheral: LPI2C1, signal: SDA, pin_signal: P1_12/WUU0_IN12/LPI2C1_SDA/LPUART2_RXD/CT2_MAT2/FLEXIO0_D20/SmartDMA_PIO8/ADC1_A10}
  - {pin_num: '6', peripheral: LPI2C1, signal: SCL, pin_signal: P1_13/TRIG_IN3/LPI2C1_SCL/LPUART2_TXD/CT2_MAT3/FLEXIO0_D21/SmartDMA_PIO9/ADC1_A11, identifier: I2C1_SCL}
  - {pin_num: '52', peripheral: LPI2C3, signal: SCL, pin_signal: P3_27/WUU0_IN30/TRIG_OUT7/LPI2C3_SCL/LPUART4_TXD/CT_INP13/CT3_MAT1/FLEXIO0_D27/PWM1_A3/SmartDMA_PIO27}
  - {pin_num: '50', peripheral: GPIO3, signal: 'GPIO, 29', pin_signal: P3_29/WUU0_IN27/TAMPER1/LPI2C3_HREQ/CT_INP3/CT3_MAT3/FLEXIO0_D29/SmartDMA_PIO29/ADC1_A22, identifier: IO3,
    direction: OUTPUT}
  - {pin_num: '49', peripheral: GPIO3, signal: 'GPIO, 30', pin_signal: P3_30/TRIG_OUT6/LPI2C3_SCLS/LPUART4_RTS_B/CT0_MAT2/FLEXIO0_D30/PWM1_A0/SmartDMA_PIO30/ADC1_A21,
    direction: OUTPUT}
  - {pin_num: '51', peripheral: LPI2C3, signal: SDA, pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C3_SDA/LPUART4_RXD/CT_INP12/CT3_MAT2/FLEXIO0_D28/PWM1_B3/SmartDMA_PIO28,
    identifier: I2C3_SDA}
  - {pin_num: '90', peripheral: GPIO0, signal: 'GPIO, 23', pin_signal: P0_23/WUU0_IN5/LPUART0_CTS_B/CT_INP3/CT0_MAT1/FLEXIO0_D7/SmartDMA_PIO13/ADC0_A13, direction: OUTPUT,
    gpio_init_state: 'true'}
  - {pin_num: '11', peripheral: SCG0, signal: EXTAL, pin_signal: P1_31/TRIG_IN4/LPI2C0_SCL/CT_INP17/FLEXIO0_D31/I3C0_SCL/EXTAL48M}
  - {pin_num: '10', peripheral: SCG0, signal: XTAL, pin_signal: P1_30/TRIG_OUT3/LPI2C0_SDA/CT_INP16/FLEXIO0_D30/I3C0_SDA/XTAL48M}
  - {pin_num: '58', peripheral: GPIO3, signal: 'GPIO, 17', pin_signal: P3_17/LPUART4_CTS_B/CT_INP9/FLEXIO0_D25/PWM1_B0/SmartDMA_PIO17, direction: INPUT, pull_select: up}
  - {pin_num: '57', peripheral: GPIO3, signal: 'GPIO, 18', pin_signal: P3_18/TAMPER5/LPUART4_RXD/CT2_MAT0/PWM0_X0/FLEXIO0_D26/PWM1_X0/SmartDMA_PIO18, direction: INPUT,
    pull_select: up}
  - {pin_num: '56', peripheral: GPIO3, signal: 'GPIO, 19', pin_signal: P3_19/TAMPER4/LPUART4_TXD/CT2_MAT1/PWM0_X1/FLEXIO0_D27/PWM1_X1/SmartDMA_PIO19, direction: INPUT,
    pull_select: up}
  - {pin_num: '55', peripheral: GPIO3, signal: 'GPIO, 20', pin_signal: P3_20/TRIG_OUT0/LPI2C3_SDA/LPUART1_RXD/CT2_MAT2/PWM0_X2/FLEXIO0_D28/PWM1_A3/SmartDMA_PIO20,
    direction: INPUT, pull_select: up}
  - {pin_num: '54', peripheral: GPIO3, signal: 'GPIO, 21', pin_signal: P3_21/TRIG_OUT1/LPI2C3_SCL/LPUART1_TXD/CT2_MAT3/PWM0_X3/FLEXIO0_D29/PWM1_B3/SmartDMA_PIO21,
    direction: INPUT, pull_select: up}
  - {pin_num: '24', peripheral: DAC0, signal: OUT, pin_signal: P2_2/TRIG_IN6/LPUART0_RTS_B/LPUART2_TXD/CT_INP12/CT2_MAT2/FLEXIO0_D10/SmartDMA_PIO26/ADC0_A4/CMP0_IN0/DAC0_OUT}
  - {pin_num: '87', peripheral: LPUART0, signal: RX, pin_signal: P0_20/WUU0_IN4/LPUART0_RXD/CT_INP0/FLEXIO0_D4/SmartDMA_PIO10/ADC0_A10}
  - {pin_num: '88', peripheral: LPUART0, signal: TX, pin_signal: P0_21/LPUART0_TXD/CT_INP1/FLEXIO0_D5/SmartDMA_PIO11/ADC0_A11}
  - {pin_num: '86', peripheral: GPIO0, signal: 'GPIO, 19', pin_signal: P0_19/WUU0_IN3/LPI2C0_SDAS/CT0_MAT3/FLEXIO0_D3/SmartDMA_PIO9/CMP1_OUT/ADC0_A9, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: '69', peripheral: LPUART1, signal: RX, pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/FLEXIO0_D16/SmartDMA_PIO8/CLKOUT}
  - {pin_num: '68', peripheral: LPUART1, signal: TX, pin_signal: P3_9/TRIG_IN4/LPSPI1_SDI/LPUART1_TXD/CT_INP5/PWM0_B1/FLEXIO0_D17/SmartDMA_PIO9}
  - {pin_num: '73', peripheral: FLEXPWM0, signal: 'A, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/LPUART3_RXD/CT_INP16/PWM0_A0/FLEXIO0_D8/PWM1_X0/SmartDMA_PIO0, identifier: PWM0,
    direction: OUTPUT}
  - {pin_num: '36', peripheral: LPSPI1, signal: IN, pin_signal: P2_15/WUU0_IN21/TRIG_OUT4/LPSPI1_SDI/LPUART1_RTS_B/CT4_MAT3/CT0_MAT2/FLEXIO0_D23/SmartDMA_PIO18/OPAMP0_OUT/ADC0_A2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO0);
    /* GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
    /* GPIO0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO0_RST_SHIFT_RSTn);
    /* LPUART0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
    /* LPSPI0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPSPI0_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* LPI2C1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C1_RST_SHIFT_RSTn);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* LPSPI1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPSPI1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* DAC0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kDAC0_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* LPI2C3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPI2C3_RST_SHIFT_RSTn);
    /* LPUART1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART1_RST_SHIFT_RSTn);

    PORT0->PCR[0] = ((PORT0->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_0 (pin 76) is configured as SWDIO. */
                     | PORT_PCR_MUX(PORT0_PCR0_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT0->PCR[1] = ((PORT0->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT0_1 (pin 77) is configured as SWCLK. */
                     | PORT_PCR_MUX(PORT0_PCR1_MUX_mux01)

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_19 (pin 86) is configured as P0_19 */
    PORT_SetPinMux(BOARD_INITPINS_RS485_EN_PORT, BOARD_INITPINS_RS485_EN_PIN, kPORT_MuxAlt0);

    PORT0->PCR[19] = ((PORT0->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_20 (pin 87) is configured as LPUART0_RXD */
    PORT_SetPinMux(BOARD_INITPINS_UART0_RX_PORT, BOARD_INITPINS_UART0_RX_PIN, kPORT_MuxAlt3);

    PORT0->PCR[20] = ((PORT0->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_21 (pin 88) is configured as LPUART0_TXD */
    PORT_SetPinMux(BOARD_INITPINS_UART0_TX_PORT, BOARD_INITPINS_UART0_TX_PIN, kPORT_MuxAlt3);

    PORT0->PCR[21] = ((PORT0->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT0_23 (pin 90) is configured as P0_23 */
    PORT_SetPinMux(BOARD_INITPINS_EN_15V_PORT, BOARD_INITPINS_EN_15V_PIN, kPORT_MuxAlt0);

    PORT0->PCR[23] = ((PORT0->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_0 (pin 91) is configured as LPSPI0_SDO */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_MOSI_PORT, BOARD_INITPINS_SPI0_MOSI_PIN, kPORT_MuxAlt2);

    PORT1->PCR[0] = ((PORT1->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_1 (pin 92) is configured as LPSPI0_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_SCK_PORT, BOARD_INITPINS_SPI0_SCK_PIN, kPORT_MuxAlt2);

    PORT1->PCR[1] = ((PORT1->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_12 (pin 5) is configured as LPI2C1_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C1_SDA_PORT, BOARD_INITPINS_I2C1_SDA_PIN, kPORT_MuxAlt2);

    PORT1->PCR[12] = ((PORT1->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_13 (pin 6) is configured as LPI2C1_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C1_SCL_PORT, BOARD_INITPINS_I2C1_SCL_PIN, kPORT_MuxAlt2);

    PORT1->PCR[13] = ((PORT1->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_2 (pin 93) is configured as LPSPI0_SDI */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_MISO_PORT, BOARD_INITPINS_SPI0_MISO_PIN, kPORT_MuxAlt2);

    PORT1->PCR[2] = ((PORT1->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_3 (pin 94) is configured as LPSPI0_PCS0 */
    PORT_SetPinMux(BOARD_INITPINS_SPI0_CS_PORT, BOARD_INITPINS_SPI0_CS_PIN, kPORT_MuxAlt2);

    PORT1->PCR[3] = ((PORT1->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT1_30 (pin 10) is configured as XTAL48M */
    PORT_SetPinMux(BOARD_INITPINS_OSC_OUT_PORT, BOARD_INITPINS_OSC_OUT_PIN, kPORT_MuxAlt0);

    PORT1->PCR[30] = ((PORT1->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_31 (pin 11) is configured as EXTAL48M */
    PORT_SetPinMux(BOARD_INITPINS_OSC_IN_PORT, BOARD_INITPINS_OSC_IN_PIN, kPORT_MuxAlt0);

    PORT1->PCR[31] = ((PORT1->PCR[31] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Disables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe0));

    /* PORT1_8 (pin 1) is configured as P1_8 */
    PORT_SetPinMux(BOARD_INITPINS_LED_PORT, BOARD_INITPINS_LED_PIN, kPORT_MuxAlt0);

    PORT1->PCR[8] = ((PORT1->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_12 (pin 34) is configured as LPSPI1_SCK */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_SCK_PORT, BOARD_INITPINS_SPI1_SCK_PIN, kPORT_MuxAlt2);

    PORT2->PCR[12] = ((PORT2->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_13 (pin 35) is configured as LPSPI1_SDO */
    PORT_SetPinMux(BOARD_INITPINS_SPI1_MOSI_PORT, BOARD_INITPINS_SPI1_MOSI_PIN, kPORT_MuxAlt2);

    PORT2->PCR[13] = ((PORT2->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT2_15 (pin 36) is configured as LPSPI1_SDI */
    PORT_SetPinMux(PORT2, 15U, kPORT_MuxAlt2);

    PORT2->PCR[15] = ((PORT2->PCR[15] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[17] = ((PORT2->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_17 (pin 38) is configured as LPSPI1_PCS0. */
                      | PORT_PCR_MUX(PORT2_PCR17_MUX_mux10)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[2] = ((PORT2->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                     /* Pin Multiplex Control: PORT2_2 (pin 24) is configured as DAC0_OUT. */
                     | PORT_PCR_MUX(PORT2_PCR2_MUX_mux00)

                     /* Input Buffer Enable: Disables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe0));

    PORT2->PCR[20] = ((PORT2->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_20 (pin 40) is configured as P2_20. */
                      | PORT_PCR_MUX(PORT2_PCR20_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[21] = ((PORT2->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pin Multiplex Control: PORT2_21 (pin 41) is configured as P2_21. */
                      | PORT_PCR_MUX(PORT2_PCR21_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    PORT2->PCR[23] = ((PORT2->PCR[23] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_MUX_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Pin Multiplex Control: PORT2_23 (pin 42) is configured as P2_23. */
                      | PORT_PCR_MUX(PORT2_PCR23_MUX_mux00)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_0 (pin 73) is configured as PWM0_A0 */
    PORT_SetPinMux(BOARD_INITPINS_PWM0_PORT, BOARD_INITPINS_PWM0_PIN, kPORT_MuxAlt5);

    PORT3->PCR[0] = ((PORT3->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_11 (pin 66) is configured as P3_11 */
    PORT_SetPinMux(BOARD_INITPINS_RESET_PORT, BOARD_INITPINS_RESET_PIN, kPORT_MuxAlt0);

    PORT3->PCR[11] = ((PORT3->PCR[11] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_12 (pin 63) is configured as P3_12 */
    PORT_SetPinMux(BOARD_INITPINS_LED_OUT_PORT, BOARD_INITPINS_LED_OUT_PIN, kPORT_MuxAlt0);

    PORT3->PCR[12] = ((PORT3->PCR[12] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_13 (pin 62) is configured as P3_13 */
    PORT_SetPinMux(BOARD_INITPINS_IO2_PORT, BOARD_INITPINS_IO2_PIN, kPORT_MuxAlt0);

    PORT3->PCR[13] = ((PORT3->PCR[13] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_16 (pin 59) is configured as P3_16 */
    PORT_SetPinMux(BOARD_INITPINS_RS485_EN2_PORT, BOARD_INITPINS_RS485_EN2_PIN, kPORT_MuxAlt0);

    PORT3->PCR[16] = ((PORT3->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_17 (pin 58) is configured as P3_17 */
    PORT_SetPinMux(BOARD_INITPINS_IN5_PORT, BOARD_INITPINS_IN5_PIN, kPORT_MuxAlt0);

    PORT3->PCR[17] = ((PORT3->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_18 (pin 57) is configured as P3_18 */
    PORT_SetPinMux(BOARD_INITPINS_IN1_PORT, BOARD_INITPINS_IN1_PIN, kPORT_MuxAlt0);

    PORT3->PCR[18] = ((PORT3->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_19 (pin 56) is configured as P3_19 */
    PORT_SetPinMux(BOARD_INITPINS_IN10_PORT, BOARD_INITPINS_IN10_PIN, kPORT_MuxAlt0);

    PORT3->PCR[19] = ((PORT3->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_20 (pin 55) is configured as P3_20 */
    PORT_SetPinMux(BOARD_INITPINS_IN6_PORT, BOARD_INITPINS_IN6_PIN, kPORT_MuxAlt0);

    PORT3->PCR[20] = ((PORT3->PCR[20] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_21 (pin 54) is configured as P3_21 */
    PORT_SetPinMux(BOARD_INITPINS_IN7_PORT, BOARD_INITPINS_IN7_PIN, kPORT_MuxAlt0);

    PORT3->PCR[21] = ((PORT3->PCR[21] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_PS_MASK | PORT_PCR_IBE_MASK)))

                      /* Pull Select: Enables internal pullup resistor. */
                      | PORT_PCR_PS(PCR_PS_ps1)

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_22 (pin 53) is configured as P3_22 */
    PORT_SetPinMux(BOARD_INITPINS_I2C3_WP_PORT, BOARD_INITPINS_I2C3_WP_PIN, kPORT_MuxAlt0);

    PORT3->PCR[22] = ((PORT3->PCR[22] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_27 (pin 52) is configured as LPI2C3_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C3_SCL_PORT, BOARD_INITPINS_I2C3_SCL_PIN, kPORT_MuxAlt2);

    PORT3->PCR[27] = ((PORT3->PCR[27] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_28 (pin 51) is configured as LPI2C3_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C3_SDA_PORT, BOARD_INITPINS_I2C3_SDA_PIN, kPORT_MuxAlt2);

    PORT3->PCR[28] = ((PORT3->PCR[28] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_29 (pin 50) is configured as P3_29 */
    PORT_SetPinMux(BOARD_INITPINS_IO3_PORT, BOARD_INITPINS_IO3_PIN, kPORT_MuxAlt0);

    PORT3->PCR[29] = ((PORT3->PCR[29] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_30 (pin 49) is configured as P3_30 */
    PORT_SetPinMux(BOARD_INITPINS_IO1_PORT, BOARD_INITPINS_IO1_PIN, kPORT_MuxAlt0);

    PORT3->PCR[30] = ((PORT3->PCR[30] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_IBE_MASK)))

                      /* Input Buffer Enable: Enables. */
                      | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_8 (pin 69) is configured as LPUART1_RXD */
    PORT_SetPinMux(BOARD_INITPINS_UART1_RX_PORT, BOARD_INITPINS_UART1_RX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[8] = ((PORT3->PCR[8] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    /* PORT3_9 (pin 68) is configured as LPUART1_TXD */
    PORT_SetPinMux(BOARD_INITPINS_UART1_TX_PORT, BOARD_INITPINS_UART1_TX_PIN, kPORT_MuxAlt3);

    PORT3->PCR[9] = ((PORT3->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_IBE_MASK)))

                     /* Input Buffer Enable: Enables. */
                     | PORT_PCR_IBE(PCR_IBE_ibe1));

    gpio_pin_config_t RS485_EN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_19 (pin 86)  */
    GPIO_PinInit(BOARD_INITPINS_RS485_EN_GPIO, BOARD_INITPINS_RS485_EN_PIN, &RS485_EN_config);

    gpio_pin_config_t EN_15V_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin 90)  */
    GPIO_PinInit(BOARD_INITPINS_EN_15V_GPIO, BOARD_INITPINS_EN_15V_PIN, &EN_15V_config);

    gpio_pin_config_t LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_8 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GPIO, BOARD_INITPINS_LED_PIN, &LED_config);

    gpio_pin_config_t IO7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_20 (pin 40)  */
    GPIO_PinInit(BOARD_INITPINS_IO7_GPIO, BOARD_INITPINS_IO7_PIN, &IO7_config);

    gpio_pin_config_t ADC_PWR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO2_21 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_ADC_PWR_GPIO, BOARD_INITPINS_ADC_PWR_PIN, &ADC_PWR_config);

    gpio_pin_config_t IN4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_23 (pin 42)  */
    GPIO_PinInit(BOARD_INITPINS_IN4_GPIO, BOARD_INITPINS_IN4_PIN, &IN4_config);

    gpio_pin_config_t RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_11 (pin 66)  */
    GPIO_PinInit(BOARD_INITPINS_RESET_GPIO, BOARD_INITPINS_RESET_PIN, &RESET_config);

    gpio_pin_config_t LED_OUT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_12 (pin 63)  */
    GPIO_PinInit(BOARD_INITPINS_LED_OUT_GPIO, BOARD_INITPINS_LED_OUT_PIN, &LED_OUT_config);

    gpio_pin_config_t IO2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_13 (pin 62)  */
    GPIO_PinInit(BOARD_INITPINS_IO2_GPIO, BOARD_INITPINS_IO2_PIN, &IO2_config);

    gpio_pin_config_t RS485_EN2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_16 (pin 59)  */
    GPIO_PinInit(BOARD_INITPINS_RS485_EN2_GPIO, BOARD_INITPINS_RS485_EN2_PIN, &RS485_EN2_config);

    gpio_pin_config_t IN5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_17 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_IN5_GPIO, BOARD_INITPINS_IN5_PIN, &IN5_config);

    gpio_pin_config_t IN1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_18 (pin 57)  */
    GPIO_PinInit(BOARD_INITPINS_IN1_GPIO, BOARD_INITPINS_IN1_PIN, &IN1_config);

    gpio_pin_config_t IN10_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_19 (pin 56)  */
    GPIO_PinInit(BOARD_INITPINS_IN10_GPIO, BOARD_INITPINS_IN10_PIN, &IN10_config);

    gpio_pin_config_t IN6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_20 (pin 55)  */
    GPIO_PinInit(BOARD_INITPINS_IN6_GPIO, BOARD_INITPINS_IN6_PIN, &IN6_config);

    gpio_pin_config_t IN7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_21 (pin 54)  */
    GPIO_PinInit(BOARD_INITPINS_IN7_GPIO, BOARD_INITPINS_IN7_PIN, &IN7_config);

    gpio_pin_config_t I2C3_WP_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PIO3_22 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_I2C3_WP_GPIO, BOARD_INITPINS_I2C3_WP_PIN, &I2C3_WP_config);

    gpio_pin_config_t IO3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_29 (pin 50)  */
    GPIO_PinInit(BOARD_INITPINS_IO3_GPIO, BOARD_INITPINS_IO3_PIN, &IO3_config);

    gpio_pin_config_t IO1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_30 (pin 49)  */
    GPIO_PinInit(BOARD_INITPINS_IO1_GPIO, BOARD_INITPINS_IO1_PIN, &IO1_config);

    /* Interrupt configuration on GPIO2_23 (pin 42): Interrupt/DMA request is disabled */
    GPIO_SetPinInterruptConfig(BOARD_INITPINS_IN4_GPIO, BOARD_INITPINS_IN4_PIN, kGPIO_InterruptStatusFlagDisabled);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
