/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXA176
package_id: MCXA176VLL
mcu_data: ksdk2_0
processor_version: 25.09.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 996b6357-640d-4ac5-8e07-01c0ca4bcd48
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma4'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'edma4_2.9.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - dmamux_devices: []
    - common_settings:
      - vars: []
      - enableHaltOnError: 'true'
      - enableDebugMode: 'false'
      - enableRoundRobinArbitration: 'fixedPriority'
      - enableGlobalChannelLink: 'true'
      - enableMasterIdReplication: 'false'
    - dma_table:
      - 0: []
    - edma_channels: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
edma_config_t DMA0_config = {
  .enableMasterIdReplication = false,
  .enableGlobalChannelLink = true,
  .enableHaltOnError = true,
  .enableDebugMode = false,
  .enableRoundRobinArbitration = false
};

/* Empty initialization function (commented out)
static void DMA0_init(void) {
} */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts:
      - 0:
        - channelId: 'int_0'
        - interrupt_t:
          - IRQn: 'DMA_CH0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '2'
          - enable_custom_name: 'false'
      - 1:
        - channelId: 'int_1'
        - interrupt_t:
          - IRQn: 'LPUART1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'true'
          - priority: '3'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'edma'
- custom_name_enabled: 'true'
- type_id: 'lpuart_2.10.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rtsWatermark: '0'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
      - swapTxdRxd: 'false'
  - edmaCfg:
    - edma_channels:
      - enable_rx_edma_channel: 'true'
      - edma_rx_channel:
        - uid: '1789210486024'
        - eDMAn: '0'
        - eDMA_source: 'kDma0RequestLPUART1Rx'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - masterIdReplicationEnable: 'noInit'
        - protectionLevel: 'noInit'
        - enable_custom_name: 'false'
      - enable_tx_edma_channel: 'false'
      - edma_tx_channel:
        - uid: '1789210486025'
        - eDMAn: '1'
        - eDMA_source: 'kDma0RequestLPUART1Tx'
        - init_channel_priority: 'false'
        - edma_channel_Preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - masterIdReplicationEnable: 'noInit'
        - protectionLevel: 'noInit'
        - enable_custom_name: 'false'
    - lpuart_edma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rtsWatermark = 0U,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true,
  .swapTxdRxd = false
};
edma_handle_t LPUART1_RX_Handle;
lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  /* Set the kDma0RequestLPUART1Rx request */
  EDMA_SetChannelMux(LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL, LPUART1_RX_DMA_REQUEST);
  /* Create the eDMA LPUART1_RX_Handle handle */
  EDMA_CreateHandle(&LPUART1_RX_Handle, LPUART1_RX_DMA_BASEADDR, LPUART1_RX_DMA_CHANNEL);
  /* Create the LPUART eDMA handle */
  LPUART_TransferCreateHandleEDMA(LPUART1_PERIPHERAL, &LPUART1_LPUART_eDMA_Handle, NULL, NULL, NULL, &LPUART1_RX_Handle);
}

/***********************************************************************************************************************
 * DAC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DAC0'
- type: 'dac_1'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'dac_1_2.1.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DAC0'
- config_sets:
  - fsl_dac:
    - dac_config:
      - fifoWatermarkLevel: '0'
      - fifoTriggerMode: 'kDAC_FIFOTriggerBySoftwareMode'
      - fifoWorkMode: 'kDAC_FIFODisabled'
      - referenceVoltageSource: 'kDAC_ReferenceVoltageSourceAlt1'
      - referenceCurrentSource: 'kDAC_ReferenceCurrentSourcePtat'
      - enableOpampBuffer: 'true'
      - periodicTriggerNumber: '0'
      - periodicTriggerWidth: '0'
      - syncTime: '0'
      - enableLowerLowPowerMode: 'false'
    - enable_dma: 'false'
    - dac_dma: 'kDAC_FIFOEmptyDMAEnable'
    - enable_DAC: 'true'
    - enable_convert: 'true'
    - convert_value: '0'
    - interrupt_config:
      - dac_interrupts: ''
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'DAC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dac_config_t DAC0_config = {
  .fifoWatermarkLevel = 0UL,
  .fifoTriggerMode = kDAC_FIFOTriggerBySoftwareMode,
  .fifoWorkMode = kDAC_FIFODisabled,
  .referenceVoltageSource = kDAC_ReferenceVoltageSourceAlt1,
  .referenceCurrentSource = kDAC_ReferenceCurrentSourcePtat,
  .enableOpampBuffer = true,
  .periodicTriggerNumber = 0UL,
  .periodicTriggerWidth = 0UL,
  .syncTime = 0UL,
  .enableLowerLowPowerMode = false,
};

static void DAC0_init(void) {
  /* Power up analog module in SPC */
  SPC_EnableActiveModeAnalogModules(SPC0, kSPC_controlDac0);
  /* Initialize the LPDAC */
  DAC_Init(DAC0_PERIPHERAL, &DAC0_config);
  /* Enable the LPDAC */
  DAC_Enable(DAC0_PERIPHERAL, true);
  /* Set LPDAC value */
  DAC_SetData(DAC0_PERIPHERAL, 0);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Interrupt vector DMA_CH0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_0_IRQN, INT_0_IRQ_PRIORITY);
  /* Interrupt vector LPUART1_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_1_IRQN, INT_1_IRQ_PRIORITY);
  /* Enable interrupt INT_0_IRQN request in the NVIC */
  EnableIRQ(INT_0_IRQN);
  /* Enable interrupt INT_1_IRQN request in the NVIC */
  EnableIRQ(INT_1_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  (void)memset(DMA0_config.channelConfig, 0, FSL_FEATURE_EDMA_INSTANCE_CHANNELn(DMA0_DMA_BASEADDR) * sizeof(edma_channel_config_t *));
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  LPUART1_init();
  DAC0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
