/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "stdlib.h"
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpuart_edma.h"
#include "fsl_spc.h"
#include "fsl_dac.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR (EDMA_Type *)DMA0
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN DMA_CH0_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 2
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER DMA_CH0_IRQHandler
/* NVIC interrupt vector ID (number). */
#define INT_1_IRQN LPUART1_IRQn
/* NVIC interrupt vector priority. */
#define INT_1_IRQ_PRIORITY 3
/* NVIC interrupt handler identifier. */
#define INT_1_IRQHANDLER LPUART1_IRQHandler
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 45000000UL
/* LPUART1 eDMA source request. */
#define LPUART1_RX_DMA_REQUEST kDma0RequestLPUART1Rx
/* Selected eDMA channel number. */
#define LPUART1_RX_DMA_CHANNEL 0
/* Used DMA device. */
#define LPUART1_RX_DMA_BASEADDR DMA0
/* BOARD_InitPeripherals defines for DAC0 */
/* Definition of peripheral ID */
#define DAC0_PERIPHERAL DAC0
/* DAC0 interrupt vector ID (number). */
#define DAC0_IRQN DAC0_IRQn
/* DAC0 interrupt handler identifier. */
#define DAC0_IRQHANDLER DAC0_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern edma_config_t DMA0_config;
extern const lpuart_config_t LPUART1_config;
extern edma_handle_t LPUART1_RX_Handle;
extern lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;
/* LPDAC configuration */
extern const dac_config_t DAC0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
