/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe0 0x00u          /*!<@brief Input Buffer Enable: Disables */
#define PCR_IBE_ibe1 0x01u          /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR21_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */
#define PORT2_PCR2_MUX_mux00 0x00u  /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT2_21 (number 41), ADC_PWR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_PWR_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_PWR_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_ADC_PWR_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ADC_PWR_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_PWR_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_PWR_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_PWR_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
